name: DiamondWorldRPG
version: '${project.version}'
main: net.relfect.task.RPG
softdepend: [Vault, ProtocolLib, HolographicDisplays, PlaceholderAPI]
api-version: 1.16
commands:
  spawner:
    aliases: [sp]
  spawners:
    aliases: [sps]
